export type Category = {
  slug: string;
  name: string;
  shortName?: string;
  tagline: string;
  emoji: string;
  image: string;
  tint: string;
  accentColor?: string;
};

export type Review = {
  id: string;
  author: string;
  location: string;
  rating: number;
  date: string;
  comment: string;
  verified: boolean;
};

export type Product = {
  id: string;
  name: string;
  brand: string;
  origin: string; // country
  flag: string; // flag emoji
  category: string; // category slug
  price: number; // LKR
  originalPrice?: number; // LKR before discount
  unit: string;
  emoji: string;
  tint?: string;
  badge?: "BESTSELLER" | "NEW" | "HOT DEAL" | "VIRAL" | "LIMITED TIME" | "COMBO" | "STAFF PICK";
  rating: number;
  stockLeft?: number;
  image?: string;
  isViral?: boolean;
  isDeal?: boolean;
  description?: string;
  ingredients?: string[];
  nutrition?: {
    calories?: string;
    servingSize?: string;
    fat?: string;
    sugar?: string;
    protein?: string;
    sodium?: string;
    carbohydrate?: string;
    electrolytes?: string;
    [key: string]: string | undefined;
  };
  tags?: string[];
  storage?: string;
  shelfLife?: string;
  bundleWith?: string[]; // paired item IDs
  bundleTitle?: string;
  bundleDiscountPercent?: number;
  reviews?: Review[];
};

export const CATEGORIES: Category[] = [
  {
    slug: "sweets",
    name: "Sweets & Chocolates",
    shortName: "Sweets",
    tagline: "Swiss chocolates, Belgian pralines & imported gummies",
    emoji: "🍫",
    image: "/images/categories/cat-sweets.jpg",
    tint: "bg-antique-card",
    accentColor: "#24140e",
  },
  {
    slug: "biscuits",
    name: "Biscuits & Cookies",
    shortName: "Biscuits",
    tagline: "Lotus Biscoff, Tim Tams, Oreos & wafer treats",
    emoji: "🍪",
    image: "/images/categories/cat-biscuits.jpg",
    tint: "bg-antique-card",
    accentColor: "#24140e",
  },
  {
    slug: "drinks",
    name: "Cold Drinks & Sodas",
    shortName: "Drinks",
    tagline: "Cold sodas, iced teas, energy drinks & Japanese sodas",
    emoji: "🥤",
    image: "/images/categories/cat-drinks.jpg",
    tint: "bg-antique-card",
    accentColor: "#24140e",
  },
  {
    slug: "health-fitness",
    name: "Health & Fitness",
    shortName: "Health & Fit",
    tagline: "Protein bars, electrolytes, shakers & vitamins",
    emoji: "💪",
    image: "/images/categories/cat-health-fitness.jpg",
    tint: "bg-antique-card",
    accentColor: "#24140e",
  },
  {
    slug: "cosmetics",
    name: "Cosmetics & Skincare",
    shortName: "Cosmetics",
    tagline: "Lip balms, sheet masks, sunscreens & lotions",
    emoji: "✨",
    image: "/images/categories/cat-cosmetics.jpg",
    tint: "bg-antique-card",
    accentColor: "#24140e",
  },
  {
    slug: "crisps",
    name: "Crisps & Savoury Snacks",
    shortName: "Crisps",
    tagline: "Pringles, Takis, Doritos & savoury munchies",
    emoji: "🥔",
    image: "/images/categories/cat-crisps.jpg",
    tint: "bg-antique-card",
    accentColor: "#24140e",
  },
  {
    slug: "baby",
    name: "Baby Care Products",
    shortName: "Baby Care",
    tagline: "Organic purees, baby formula, wipes & teething treats",
    emoji: "🍼",
    image: "/images/categories/cat-baby.jpg",
    tint: "bg-antique-card",
    accentColor: "#24140e",
  },
  {
    slug: "cupboard",
    name: "Cupboard & Pantry Staples",
    shortName: "Cupboard",
    tagline: "Pantry staples, spreads, pastas, sauces & breakfast cereals",
    emoji: "🫙",
    image: "/images/categories/cat-cupboard.jpg",
    tint: "bg-antique-card",
    accentColor: "#24140e",
  },
  {
    slug: "frozen",
    name: "Dairy & Frozen Treats",
    shortName: "Frozen",
    tagline: "Häagen-Dazs ice cream, mochi bites, butter & desserts",
    emoji: "🍦",
    image: "/images/categories/cat-frozen.jpg",
    tint: "bg-antique-card",
    accentColor: "#24140e",
  },
  {
    slug: "viral",
    name: "Viral Internet Drops",
    shortName: "Viral Drops",
    tagline: "Limited time internet sensations & rare foreign drops",
    emoji: "🔥",
    image: "/images/categories/cat-viral.jpg",
    tint: "bg-antique-card",
    accentColor: "#b87928",
  },
];

export const PRODUCTS: Product[] = [
  // ==================== 1. SWEETS ====================
  {
    id: "sweets-lindt-70",
    name: "Lindt Excellence 70% Dark",
    brand: "Lindt",
    origin: "Switzerland",
    flag: "🇨🇭",
    category: "sweets",
    price: 2450,
    unit: "100g bar",
    emoji: "🍫",
    badge: "BESTSELLER",
    rating: 4.9,
    image: "/images/products/choc-lindt-70.png",
    description: "Crafted by Swiss Master Chocolatiers since 1845, Lindt Excellence 70% Dark Chocolate features intense cocoa aromas balanced with subtle hints of vanilla and dried red berries. Direct air-freight import guaranteeing silky snap and pure melt.",
    ingredients: ["Cocoa mass", "Sugar", "Cocoa butter", "Natural bourbon vanilla bean"],
    nutrition: { calories: "566 kcal / 100g", servingSize: "20g (2 squares)", fat: "41g", sugar: "29g", protein: "9.5g", sodium: "40mg" },
    tags: ["Swiss Made", "Dark Chocolate", "Vegetarian", "Direct Import", "Non-GMO"],
    storage: "Store in a cool, dry place between 14°C and 18°C. Keep away from direct sunlight.",
    shelfLife: "Best Before: 12 months from import date",
    bundleWith: ["biscuits-lotus-spread", "drinks-arizona-green"],
    bundleTitle: "The Swiss Connoisseur Afternoon Pair",
    bundleDiscountPercent: 12,
    reviews: [
      { id: "r1", author: "Dr. K. Jayawardena", location: "Colombo 07", rating: 5, date: "2 days ago", comment: "Arrived in insulated packaging without a trace of melting. Absolutely authentic Swiss batch.", verified: true },
      { id: "r2", author: "Shenali F.", location: "Dehiwala", rating: 5, date: "1 week ago", comment: "The 70% dark has that deep roasted cocoa profile. Pair it with an espresso!", verified: true },
    ],
  },
  {
    id: "sweets-toblerone",
    name: "Toblerone Honey & Almond Bar",
    brand: "Toblerone",
    origin: "Switzerland",
    flag: "🇨🇭",
    category: "sweets",
    price: 1850,
    unit: "100g bar",
    emoji: "🍫",
    badge: "BESTSELLER",
    rating: 4.8,
    image: "/images/products/choc-toblerone.png",
    description: "Iconic triangular Swiss milk chocolate embedded with chewy honey and almond nougat. Direct Bern, Switzerland import sealed for freshness.",
    ingredients: ["Sugar", "Whole milk powder", "Cocoa butter", "Honey (3%)", "Almonds (1.6%)", "Egg white"],
    nutrition: { calories: "525 kcal / 100g", servingSize: "33g (3 peaks)", fat: "29g", sugar: "59g", protein: "5.4g", sodium: "60mg" },
    tags: ["Swiss Import", "Milk Chocolate", "Vegetarian", "Halal Compliant"],
    storage: "Keep in a cool dry pantry. Ideal temperature 16°C – 20°C.",
    shelfLife: "Best Before: 10 months",
    bundleWith: ["biscuits-timtam-orig", "drinks-dr-pepper"],
    bundleTitle: "Classic European Sweet Tooth Bundle",
    bundleDiscountPercent: 10,
    reviews: [
      { id: "r3", author: "M. Naleer", location: "Mount Lavinia", rating: 5, date: "3 days ago", comment: "Genuine Swiss Toblerone, crisp nougat bits inside.", verified: true }
    ],
  },
  {
    id: "sweets-ferrero-16",
    name: "Ferrero Rocher 16-Piece Box",
    brand: "Ferrero Rocher",
    origin: "Italy",
    flag: "🇮🇹",
    category: "sweets",
    price: 4950,
    originalPrice: 5500,
    unit: "200g box (16 pcs)",
    emoji: "🌰",
    badge: "HOT DEAL",
    rating: 4.9,
    image: "/images/products/choc-ferrero-16.png",
    description: "Crispy wafer sphere with a whole roasted hazelnut core, enveloped in smooth hazelnut cream and fine milk chocolate with chopped hazelnuts. Presented in a premium golden gift box.",
    ingredients: ["Milk chocolate 30%", "Hazelnuts (28.5%)", "Sugar", "Palm oil", "Wheat flour", "Whey powder"],
    nutrition: { calories: "603 kcal / 100g", servingSize: "1 piece (12.5g)", fat: "42.7g", sugar: "39.9g", protein: "8.2g", sodium: "60mg" },
    tags: ["Italian Import", "Gift Box", "Vegetarian"],
    storage: "Store in ambient climate below 20°C.",
    shelfLife: "Best Before: 8 months",
    bundleWith: ["sweets-lindt-70", "drinks-redbull-sugarfree"],
    bundleTitle: "Luxury Italian & Swiss Gift Trio",
    bundleDiscountPercent: 15,
    reviews: [
      { id: "r4", author: "Nisansala P.", location: "Kalubowila", rating: 5, date: "4 days ago", comment: "Perfect condition for gifting. Same-day delivery was under 2 hours.", verified: true }
    ],
  },
  {
    id: "sweets-kinder-bueno",
    name: "Kinder Bueno Crispy Hazelnut",
    brand: "Kinder",
    origin: "Poland",
    flag: "🇵🇱",
    category: "sweets",
    price: 850,
    unit: "43g (2 bars)",
    emoji: "🍫",
    rating: 4.7,
    image: "/images/products/choc-kinder-bueno.png",
    description: "Crispy wafer fingers filled with creamy hazelnut filling and topped with dark chocolate drizzle. Ultra-light, crispy, and indulgent.",
    ingredients: ["Milk chocolate 31.5%", "Sugar", "Palm oil", "Wheat flour", "Hazelnuts (10.8%)", "Skimmed milk powder"],
    nutrition: { calories: "122 kcal / bar", servingSize: "1 bar (21.5g)", fat: "8g", sugar: "8.9g", protein: "1.9g", sodium: "23mg" },
    tags: ["European Import", "Snack Size"],
    storage: "Keep in a cool dry space.",
    shelfLife: "Best Before: 9 months",
    bundleWith: ["drinks-arizona-green", "crisps-pringles-sourcream"],
    bundleTitle: "Quick Afternoon Refresher Pack",
    bundleDiscountPercent: 10,
  },
  {
    id: "sweets-milka-oreo",
    name: "Milka Alpine Milk Oreo Chocolate",
    brand: "Milka",
    origin: "Germany",
    flag: "🇩🇪",
    category: "sweets",
    price: 2150,
    unit: "100g bar",
    emoji: "🐮",
    badge: "NEW",
    rating: 4.8,
    image: "/images/products/choc-milka-oreo.png",
    description: "100% Alpine milk chocolate encasing crunchy Oreo biscuit pieces and smooth vanilla cream. Made in Germany with authentic Alpine milk.",
    ingredients: ["Alpine milk chocolate 50%", "Oreo cookie pieces 16%", "Vanilla creme filling 34%"],
    nutrition: { calories: "555 kcal / 100g", servingSize: "20g", fat: "34g", sugar: "50g", protein: "5.6g", sodium: "170mg" },
    tags: ["German Import", "Alpine Milk", "Vegetarian"],
    storage: "Store dry at 15°C – 18°C.",
    shelfLife: "Best Before: 10 months",
    bundleWith: ["biscuits-lotus-biscoff-250", "drinks-dr-pepper"],
    bundleTitle: "Double Cookie & Milk Combo",
    bundleDiscountPercent: 12,
  },
  {
    id: "sweets-haribo-goldbears",
    name: "Haribo Goldbears Fruity Gummy",
    brand: "Haribo",
    origin: "Germany",
    flag: "🇩🇪",
    category: "sweets",
    price: 1350,
    unit: "175g share bag",
    emoji: "🐻",
    rating: 4.7,
    image: "/images/products/candy-haribo.png",
    description: "The world's original gummy bears featuring 6 mouth-watering real fruit flavors: Apple, Strawberry, Raspberry, Orange, Lemon, and Pineapple.",
    ingredients: ["Glucose syrup", "Sugar", "Gelatine", "Dextrose", "Fruit juice from concentrate", "Citric acid"],
    nutrition: { calories: "343 kcal / 100g", servingSize: "25g", fat: "<0.5g", sugar: "46g", protein: "6.9g", sodium: "30mg" },
    tags: ["German Import", "Fat Free", "Original Recipe"],
    storage: "Store in ambient pantry.",
    shelfLife: "Best Before: 14 months",
    bundleWith: ["crisps-takis-fuego", "drinks-ramune-soda"],
    bundleTitle: "Tangy Sweet & Spicy Movie Pack",
    bundleDiscountPercent: 10,
  },
  {
    id: "sweets-reeses-peanut",
    name: "Reese's Peanut Butter Cups 3pk",
    brand: "Reese's",
    origin: "USA",
    flag: "🇺🇸",
    category: "sweets",
    price: 1250,
    unit: "51g pack (3 cups)",
    emoji: "🥜",
    rating: 4.8,
    image: "/images/products/choc-reeses-cups.png",
    description: "Classic American combination of rich Hershey milk chocolate and salty-sweet roasted peanut butter centers. Direct Pennsylvania import.",
    ingredients: ["Milk chocolate", "Peanuts", "Sugar", "Dextrose", "Salt", "TBHQ preservative"],
    nutrition: { calories: "260 kcal / pack", servingSize: "3 cups", fat: "15g", sugar: "24g", protein: "5g", sodium: "190mg" },
    tags: ["USA Import", "Peanut Butter", "Gluten Free"],
    storage: "Store below 20°C.",
    shelfLife: "Best Before: 9 months",
    bundleWith: ["drinks-prime-hydration", "crisps-doritos-nacho"],
    bundleTitle: "All-American Snack Stash",
    bundleDiscountPercent: 10,
  },

  // ==================== 2. BISCUITS ====================
  {
    id: "biscuits-lotus-biscoff-250",
    name: "Lotus Biscoff Caramelised Cookies",
    brand: "Lotus Biscoff",
    origin: "Belgium",
    flag: "🇧🇪",
    category: "biscuits",
    price: 1650,
    unit: "250g pack (32 pcs)",
    emoji: "🍪",
    badge: "BESTSELLER",
    rating: 4.9,
    description: "The original Belgian speculoos cookie with a uniquely crunchy bite and distinctive caramelized cinnamon flavour. Ideal companion for tea, coffee, or dessert toppings.",
    ingredients: ["Wheat flour", "Sugar", "Vegetable oils (palm, rapeseed)", "Candy sugar syrup", "Sodium hydrogen carbonate", "Cinnamon", "Salt"],
    nutrition: { calories: "484 kcal / 100g", servingSize: "2 cookies (15.6g)", fat: "19g", sugar: "38.1g", protein: "4.9g", sodium: "360mg" },
    tags: ["Belgian Import", "Vegan", "No Artificial Colors", "Non-GMO"],
    storage: "Store in a cool, dry place. Reseal after opening to maintain crunch.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["cupboard-lotus-spread", "sweets-lindt-70"],
    bundleTitle: "Ultimate Lotus Biscoff Experience Set",
    bundleDiscountPercent: 12,
    reviews: [
      { id: "r5", author: "Tanya M.", location: "Colombo 03", rating: 5, date: "Yesterday", comment: "Unbeatable crunch! Fresh Belgian batch with long expiry.", verified: true }
    ],
  },
  {
    id: "biscuits-timtam-orig",
    name: "Arnott's Tim Tam Original Double Pack",
    brand: "Arnott's",
    origin: "Australia",
    flag: "🇦🇺",
    category: "biscuits",
    price: 2850,
    unit: "200g pack (11 pcs)",
    emoji: "🇦🇺",
    badge: "BESTSELLER",
    rating: 4.9,
    description: "Australia's most loved chocolate biscuit! Two crunchy chocolate malt biscuits separated by light chocolate cream and smothered in real chocolate.",
    ingredients: ["Sugar", "Wheat flour", "Vegetable oil", "Milk solids", "Cocoa butter", "Cocoa mass", "Golden syrup"],
    nutrition: { calories: "518 kcal / 100g", servingSize: "1 biscuit (18.3g)", fat: "27.3g", sugar: "44.6g", protein: "4.6g", sodium: "135mg" },
    tags: ["Australian Direct", "Real Chocolate", "Bite & Sip Ready"],
    storage: "Keep in air-conditioned storage or refrigerator in tropical climates.",
    shelfLife: "Best Before: 8 months",
    bundleWith: ["sweets-toblerone", "drinks-redbull-sugarfree"],
    bundleTitle: "Aussie Brekkie & Chill Pair",
    bundleDiscountPercent: 10,
  },
  {
    id: "biscuits-oreo-japan-matcha",
    name: "Oreo Japan Uji Matcha Green Tea",
    brand: "Oreo",
    origin: "Japan",
    flag: "🇯🇵",
    category: "biscuits",
    price: 2450,
    originalPrice: 2850,
    unit: "194g family pack",
    emoji: "🍵",
    badge: "HOT DEAL",
    rating: 4.8,
    description: "Limited Japanese release combining dark cocoa sandwich biscuits with real Kyoto Uji green tea matcha creme. Subtly sweet with earthy tea notes.",
    ingredients: ["Wheat flour", "Sugar", "Vegetable oil", "Matcha powder from Kyoto", "Cocoa powder", "Cornstarch"],
    nutrition: { calories: "490 kcal / 100g", servingSize: "2 cookies", fat: "22g", sugar: "36g", protein: "5.1g", sodium: "220mg" },
    tags: ["Japanese Import", "Kyoto Matcha", "Limited Edition"],
    storage: "Store dry away from humidity.",
    shelfLife: "Best Before: 6 months",
    bundleWith: ["drinks-ramune-soda", "viral-dubai-kunafa-choc"],
    bundleTitle: "Tokyo Gourmet Tea & Snack Trio",
    bundleDiscountPercent: 14,
  },
  {
    id: "biscuits-loacker-quadratini",
    name: "Loacker Quadratini Hazelnut Wafers",
    brand: "Loacker",
    origin: "Italy",
    flag: "🇮🇹",
    category: "biscuits",
    price: 1950,
    unit: "250g bag",
    emoji: "🧇",
    rating: 4.8,
    description: "Bite-sized crispy Italian wafers layered with four layers of rich cream made from 100% Italian hazelnuts roasted in the Alps.",
    ingredients: ["Wheat flour", "Coconut oil", "Glucose syrup", "Hazelnuts 9%", "Whey powder", "Soy flour"],
    nutrition: { calories: "516 kcal / 100g", servingSize: "30g", fat: "27g", sugar: "29g", protein: "7.7g", sodium: "140mg" },
    tags: ["Italian Alps", "100% Roasted Hazelnuts", "No Added Flavorings"],
    storage: "Keep in a cool dry pantry.",
    shelfLife: "Best Before: 11 months",
    bundleWith: ["drinks-arizona-green", "sweets-ferrero-16"],
    bundleTitle: "Italian Hazelnut Crunch Bundle",
    bundleDiscountPercent: 10,
  },
  {
    id: "biscuits-nutella-biscuits",
    name: "Nutella Biscuits Crunchy Pouch",
    brand: "Nutella",
    origin: "Italy",
    flag: "🇮🇹",
    category: "biscuits",
    price: 3250,
    unit: "304g resealable bag",
    emoji: "🌰",
    badge: "VIRAL",
    rating: 5.0,
    description: "Crunchy golden baked wheat biscuits with a heart of creamy Nutella hazelnut spread. The ultimate Italian snack revolution.",
    ingredients: ["Hazelnut spread with cocoa 40% (Nutella)", "Wheat flour 32%", "Vegetable fat", "Cane sugar 8.5%", "Lactose", "Wheat bran"],
    nutrition: { calories: "513 kcal / 100g", servingSize: "3 biscuits (41g)", fat: "25.1g", sugar: "35.3g", protein: "7.2g", sodium: "230mg" },
    tags: ["Italian Import", "Authentic Nutella Core", "Resealable Pouch"],
    storage: "Store at room temperature 18°C – 24°C.",
    shelfLife: "Best Before: 7 months",
    bundleWith: ["drinks-dr-pepper", "sweets-kinder-bueno"],
    bundleTitle: "Ferrero & Nutella Lovers Box",
    bundleDiscountPercent: 12,
  },

  // ==================== 3. DRINKS ====================
  {
    id: "drinks-arizona-green",
    name: "AriZona Green Tea with Ginseng & Honey",
    brand: "AriZona",
    origin: "USA",
    flag: "🇺🇸",
    category: "drinks",
    price: 1450,
    unit: "680ml tallboy can",
    emoji: "🍵",
    badge: "BESTSELLER",
    rating: 4.8,
    description: "America's #1 green tea made with 100% natural green tea leaves, real Sue Bee orange blossom honey, and Panax ginseng. Served in the iconic cherry blossom tallboy can.",
    ingredients: ["Premium brewed green tea", "High fructose corn syrup", "Honey", "Citric acid", "Natural flavors", "Ginseng extract", "Ascorbic acid (Vit C)"],
    nutrition: { calories: "70 kcal / 240ml", servingSize: "240ml", fat: "0g", sugar: "17g", protein: "0g", sodium: "10mg" },
    tags: ["USA Direct", "Natural Honey", "Ginseng Boost", "100% Real Tea"],
    storage: "Best served chilled. Refrigerate after opening.",
    shelfLife: "Best Before: 18 months",
    bundleWith: ["crisps-pringles-sourcream", "sweets-lindt-70"],
    bundleTitle: "Chilled Afternoon Reset Combo",
    bundleDiscountPercent: 10,
    reviews: [
      { id: "r6", author: "Rehan K.", location: "Nugegoda", rating: 5, date: "3 days ago", comment: "Huge 680ml can, authentic US recipe. So refreshing over ice!", verified: true }
    ],
  },
  {
    id: "drinks-redbull-sugarfree",
    name: "Red Bull Energy Drink Sugarfree",
    brand: "Red Bull",
    origin: "Austria",
    flag: "🇦🇹",
    category: "drinks",
    price: 1150,
    unit: "250ml slim can",
    emoji: "⚡",
    rating: 4.7,
    description: "Original Austrian Red Bull formula without sugar. Gives you wings with premium caffeine, taurine, B-group vitamins, and pure Alpine water.",
    ingredients: ["Carbonated water", "Taurine 0.4%", "Caffeine 0.03%", "B-group vitamins (B3, B5, B6, B12)", "Aspartame", "Acesulfame K"],
    nutrition: { calories: "3 kcal / 100ml", servingSize: "250ml can", fat: "0g", sugar: "0g", protein: "0g", sodium: "50mg" },
    tags: ["Austrian Import", "Zero Sugar", "High Caffeine (80mg)"],
    storage: "Serve ice cold.",
    shelfLife: "Best Before: 24 months",
    bundleWith: ["health-grenade-carb-killa", "crisps-takis-blue-heat"],
    bundleTitle: "High-Focus Study & Workout Combo",
    bundleDiscountPercent: 12,
  },
  {
    id: "drinks-dr-pepper",
    name: "Dr Pepper Original 23 Flavors",
    brand: "Dr Pepper",
    origin: "USA",
    flag: "🇺🇸",
    category: "drinks",
    price: 950,
    unit: "355ml can",
    emoji: "🥤",
    badge: "BESTSELLER",
    rating: 4.8,
    description: "The unique 23 signature blend of cherry, spice, and vanilla flavors that has delighted American soda lovers since 1885.",
    ingredients: ["Carbonated water", "High fructose corn syrup", "Caramel color", "Phosphoric acid", "Natural and artificial flavors", "Sodium benzoate", "Caffeine"],
    nutrition: { calories: "150 kcal / can", servingSize: "355ml", fat: "0g", sugar: "40g", protein: "0g", sodium: "55mg" },
    tags: ["USA Direct", "Original 23 Flavors", "Caffeinated"],
    storage: "Serve chilled over ice.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["crisps-doritos-nacho", "sweets-reeses-peanut"],
    bundleTitle: "All-American Late Night Munchies",
    bundleDiscountPercent: 10,
  },
  {
    id: "drinks-ramune-soda",
    name: "Hata Ramune Marble Soda Original",
    brand: "Hata",
    origin: "Japan",
    flag: "🇯🇵",
    category: "drinks",
    price: 1250,
    unit: "200ml glass bottle",
    emoji: "🇯🇵",
    badge: "VIRAL",
    rating: 4.9,
    description: "Traditional Japanese Codd-neck glass bottle with the iconic pop marble seal. Refreshing crisp citrus-bubblegum cider flavor.",
    ingredients: ["Carbonated water", "High fructose corn syrup", "Sugar", "Citric acid", "Flavoring"],
    nutrition: { calories: "80 kcal / bottle", servingSize: "200ml", fat: "0g", sugar: "20g", protein: "0g", sodium: "0mg" },
    tags: ["Japanese Import", "Marble Pop Glass", "Festive Favorite"],
    storage: "Store dry. Pop marble to open.",
    shelfLife: "Best Before: 15 months",
    bundleWith: ["biscuits-oreo-japan-matcha", "viral-samyang-buldak-2x"],
    bundleTitle: "Tokyo Night Market Refreshment Set",
    bundleDiscountPercent: 12,
  },
  {
    id: "drinks-prime-hydration",
    name: "Prime Hydration Drink Ice Pop",
    brand: "Prime",
    origin: "USA",
    flag: "🇺🇸",
    category: "drinks",
    price: 2450,
    originalPrice: 2950,
    unit: "500ml bottle",
    emoji: "🧊",
    badge: "HOT DEAL",
    rating: 4.8,
    description: "Viral hydration beverage packed with 10% coconut water, 250mg BCAAs, B vitamins, antioxidants, and 834mg electrolytes. Refreshing Cherry-Lime-Blue Raspberry Ice Pop flavor.",
    ingredients: ["Filtered water", "Coconut water from concentrate (10.5%)", "Citric acid", "Dipotassium phosphate", "Magnesium citrate", "Natural flavor", "Sucralose", "BCAAs (L-Isoleucine, L-Leucine, L-Valine)"],
    nutrition: { calories: "20 kcal / bottle", servingSize: "500ml", fat: "0g", sugar: "2g", protein: "0g", sodium: "10mg", electrolytes: "834mg" },
    tags: ["USA Import", "Electrolytes", "10% Coconut Water", "Zero Added Sugar"],
    storage: "Refrigerate after opening.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["health-c4-preworkout", "health-grenade-carb-killa"],
    bundleTitle: "Ultimate Hydration & Performance Stack",
    bundleDiscountPercent: 15,
  },

  // ==================== 4. HEALTH & FITNESS ====================
  {
    id: "health-grenade-carb-killa",
    name: "Grenade Carb Killa White Choc Salted Peanut",
    brand: "Grenade",
    origin: "United Kingdom",
    flag: "🇬🇧",
    category: "health-fitness",
    price: 2650,
    unit: "60g protein bar",
    emoji: "💪",
    badge: "BESTSELLER",
    rating: 4.9,
    description: "Triple-layered high-protein, low-sugar bar featuring 20g of premium protein, crunchy peanut bits, and smooth white chocolate coating. Less than 2g sugar per bar.",
    ingredients: ["White chocolate with sweetener 31%", "Protein blend (calcium caseinate, whey protein isolate)", "Hydrolysed beef gelatine", "Peanuts (8.5%)", "Soy crisp"],
    nutrition: { calories: "217 kcal", servingSize: "60g bar", fat: "9.8g", sugar: "1.7g", protein: "20g", sodium: "280mg" },
    tags: ["UK Direct", "20g Protein", "<2g Sugar", "High Fiber"],
    storage: "Store in ambient climate below 22°C.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["health-applied-bcaa", "drinks-redbull-sugarfree"],
    bundleTitle: "Lean Muscle Snack Stack",
    bundleDiscountPercent: 12,
  },
  {
    id: "health-c4-preworkout",
    name: "Cellucor C4 Original Pre-Workout Fruit Punch",
    brand: "Cellucor",
    origin: "USA",
    flag: "🇺🇸",
    category: "health-fitness",
    price: 14500,
    originalPrice: 16500,
    unit: "390g tub (60 servings)",
    emoji: "⚡",
    badge: "HOT DEAL",
    rating: 4.8,
    description: "America's legendary #1 selling pre-workout powder. Loaded with 150mg caffeine, CarnoSyn Beta-Alanine, and Creatine Nitrate for explosive energy and focus.",
    ingredients: ["CarnoSyn Beta-Alanine 1.6g", "Micronized Creatine Monohydrate 1g", "Arginine AKG 1g", "Explosive Energy Blend (Caffeine Anhydrous 150mg, Velvet Bean extract)"],
    nutrition: { calories: "0 kcal", servingSize: "1 scoop (6.5g)", fat: "0g", sugar: "0g", protein: "0g", sodium: "0mg" },
    tags: ["USA Direct", "60 Servings", "150mg Caffeine", "Explosive Energy"],
    storage: "Keep tightly sealed in a dry cool place.",
    shelfLife: "Best Before: 24 months",
    bundleWith: ["health-applied-bcaa", "drinks-prime-hydration"],
    bundleTitle: "Hardcore Gym Energy & Recovery Bundle",
    bundleDiscountPercent: 15,
  },
  {
    id: "health-applied-bcaa",
    name: "Applied Nutrition Amino-Hydrate BCAA",
    brand: "Applied Nutrition",
    origin: "United Kingdom",
    flag: "🇬🇧",
    category: "health-fitness",
    price: 11500,
    unit: "450g tub (32 servings)",
    emoji: "🧪",
    rating: 4.8,
    description: "Intra-workout hydration formula delivering 7.2g BCAAs per serving combined with coconut water powder, glutamine, and essential electrolyte salts.",
    ingredients: ["BCAA 2:1:1 Blend (L-Leucine, L-Isoleucine, L-Valine)", "L-Glutamine", "Coconut Water Powder", "Vitamin B6", "Electrolyte Blend (Sodium, Potassium, Magnesium)"],
    nutrition: { calories: "0 kcal", servingSize: "14g scoop", fat: "0g", sugar: "0g", protein: "7.2g amino", sodium: "120mg" },
    tags: ["UK Import", "Informed Sport Tested", "Sugar Free"],
    storage: "Store dry.",
    shelfLife: "Best Before: 20 months",
    bundleWith: ["health-grenade-carb-killa", "drinks-redbull-sugarfree"],
    bundleTitle: "Endurance & Recovery Trio",
    bundleDiscountPercent: 10,
  },
  {
    id: "health-barebells-caramel",
    name: "Barebells Caramel Cashew Protein Bar",
    brand: "Barebells",
    origin: "Sweden",
    flag: "🇸🇪",
    category: "health-fitness",
    price: 2850,
    unit: "55g bar",
    emoji: "🥜",
    badge: "VIRAL",
    rating: 5.0,
    description: "Scandinavia's cult-favorite protein snack! Delicious gooey caramel, roasted cashew nuts, and silky milk chocolate coating with 20g protein and no added sugar.",
    ingredients: ["Milk protein", "Milk chocolate with sweetener (sweetener maltitol, cocoa butter, whole milk powder, cocoa mass)", "Collagen peptides", "Cashew nuts (7.5%)"],
    nutrition: { calories: "199 kcal", servingSize: "55g bar", fat: "8.3g", sugar: "1.7g", protein: "20g", sodium: "140mg" },
    tags: ["Swedish Import", "No Added Sugar", "20g High Protein"],
    storage: "Keep in a cool dry pantry.",
    shelfLife: "Best Before: 10 months",
    bundleWith: ["sweets-lindt-70", "drinks-arizona-green"],
    bundleTitle: "Gourmet Guilt-Free Snack Box",
    bundleDiscountPercent: 10,
  },

  // ==================== 5. COSMETICS ====================
  {
    id: "cosmetics-carmex-cherry",
    name: "Carmex Daily Care Moisturising Cherry Lip Balm",
    brand: "Carmex",
    origin: "USA",
    flag: "🇺🇸",
    category: "cosmetics",
    price: 1450,
    unit: "10g squeeze tube",
    emoji: "🍒",
    badge: "BESTSELLER",
    rating: 4.9,
    description: "Iconic medicated lip balm formulated with soothing camphor, menthol, beeswax, and SPF 15 protection. Heals cracked, dry lips instantly with a sweet cherry scent.",
    ingredients: ["Petrolatum", "Lanolin", "Beeswax", "Cetyl esters", "Theobroma cacao seed butter", "Camphor", "Menthol", "Octinoxate (Sunscreen)"],
    tags: ["USA Direct", "SPF 15", "Intense Hydration", "Cruelty Free"],
    storage: "Store below 25°C.",
    shelfLife: "Best Before: 24 months",
    bundleWith: ["cosmetics-cerave-cleanser", "cosmetics-beauty-joseon-sun"],
    bundleTitle: "Daily Skin Barrier Essentials",
    bundleDiscountPercent: 12,
  },
  {
    id: "cosmetics-cerave-cleanser",
    name: "CeraVe Hydrating Facial Cleanser for Normal to Dry Skin",
    brand: "CeraVe",
    origin: "USA",
    flag: "🇺🇸",
    category: "cosmetics",
    price: 6850,
    originalPrice: 7500,
    unit: "236ml pump bottle",
    emoji: "🧴",
    badge: "BESTSELLER",
    rating: 4.9,
    description: "Dermatologist-developed gentle non-foaming lotion cleanser containing 3 essential ceramides (1, 3, 6-II) and hyaluronic acid. Cleanses without stripping the natural skin barrier.",
    ingredients: ["Aqua", "Glycerin", "Cetearyl alcohol", "Ceramide NP", "Ceramide AP", "Ceramide EOP", "Hyaluronic acid", "Cholesterol", "Phytosphingosine"],
    tags: ["USA Direct", "Fragrance Free", "Non-Comedogenic", "National Eczema Association Accepted"],
    storage: "Keep in bathroom cabinet at room temperature.",
    shelfLife: "Best Before: 30 months",
    bundleWith: ["cosmetics-beauty-joseon-sun", "cosmetics-carmex-cherry"],
    bundleTitle: "Derm-Approved Daily Routine",
    bundleDiscountPercent: 15,
  },
  {
    id: "cosmetics-beauty-joseon-sun",
    name: "Beauty of Joseon Relief Sun: Rice + Probiotics SPF50+",
    brand: "Beauty of Joseon",
    origin: "South Korea",
    flag: "🇰🇷",
    category: "cosmetics",
    price: 5450,
    unit: "50ml tube",
    emoji: "☀️",
    badge: "VIRAL",
    rating: 5.0,
    description: "The global K-Beauty viral sensation! Lightweight organic chemical sunscreen enriched with 30% rice extract and fermented grain probiotics. Zero white cast, absorbs like a hydrating moisturizer.",
    ingredients: ["Water", "Oryza Sativa (Rice) Extract (30%)", "Probiotics Grain Complex", "Niacinamide", "Uvinul A Plus", "Tinosorb S"],
    tags: ["K-Beauty Authentic", "SPF50+ PA++++", "Zero White Cast", "Vegan"],
    storage: "Keep away from heat.",
    shelfLife: "Best Before: 24 months",
    bundleWith: ["cosmetics-cerave-cleanser", "cosmetics-carmex-cherry"],
    bundleTitle: "Korean Glow Glass-Skin Trio",
    bundleDiscountPercent: 15,
  },
  {
    id: "cosmetics-vaseline-rosy",
    name: "Vaseline Lip Therapy Rosy Lips Tin",
    brand: "Vaseline",
    origin: "United Kingdom",
    flag: "🇬🇧",
    category: "cosmetics",
    price: 1250,
    unit: "20g tin",
    emoji: "🌹",
    rating: 4.7,
    description: "Clinically proven to heal and protect dry lips. Formulated with 100% pure triple-purified Vaseline Jelly, almond oil, and a subtle rose-tinted shine.",
    ingredients: ["Petrolatum", "Rosa Damascena Flower Oil", "Prunus Amygdalus Dulcis (Sweet Almond) Oil", "Aroma", "Linalool", "CI 73360"],
    tags: ["UK Direct", "Subtle Rose Tint", "Non-Sticky"],
    storage: "Room temperature.",
    shelfLife: "Best Before: 36 months",
    bundleWith: ["cosmetics-carmex-cherry", "cosmetics-beauty-joseon-sun"],
    bundleTitle: "Pocket Lip & Glow Duo",
    bundleDiscountPercent: 10,
  },

  // ==================== 6. CRISPS ====================
  {
    id: "crisps-takis-fuego",
    name: "Takis Fuego Hot Chili Pepper & Lime Rolled Chips",
    brand: "Takis",
    origin: "Mexico",
    flag: "🇲🇽",
    category: "crisps",
    price: 2350,
    originalPrice: 2750,
    unit: "280g mega bag",
    emoji: "🌶️",
    badge: "VIRAL",
    rating: 4.9,
    description: "The world-famous rolled corn tortilla chips coated in an intensely fiery blend of Mexican hot chili peppers and zesty tangy lime. Super crunchy and unmistakably spicy.",
    ingredients: ["Corn masa flour", "Vegetable oil (palm/soybean)", "Seasoning (salt, maltodextrin, citric acid, sugar, monosodium glutamate, onion powder, red 40 lake, chili pepper)"],
    nutrition: { calories: "150 kcal / 28g", servingSize: "28g (approx 12 chips)", fat: "8g", sugar: "1g", protein: "2g", sodium: "420mg" },
    tags: ["Authentic Mexican Import", "Extreme Crunch", "Hot & Tangy"],
    storage: "Seal tightly after opening to preserve intense crunch.",
    shelfLife: "Best Before: 9 months",
    bundleWith: ["drinks-arizona-green", "viral-samyang-buldak-2x"],
    bundleTitle: "Extreme Heat & Cool Down Challenge Pack",
    bundleDiscountPercent: 12,
  },
  {
    id: "crisps-pringles-sourcream",
    name: "Pringles Sour Cream & Onion Stack",
    brand: "Pringles",
    origin: "Belgium",
    flag: "🇧🇪",
    category: "crisps",
    price: 1650,
    unit: "165g can",
    emoji: "🥔",
    badge: "BESTSELLER",
    rating: 4.8,
    description: "The classic hyperbolic paraboloid crisps stacked in the resealable can. Savory sour cream and zesty onion powder seasoned on every crisp.",
    ingredients: ["Dehydrated potatoes", "Sunflower oil", "Wheat flour", "Corn flour", "Sour cream seasoning 5.5% (onion powder, sour cream powder, dextrose, sweet whey powder)"],
    nutrition: { calories: "515 kcal / 100g", servingSize: "30g (approx 16 crisps)", fat: "32g", sugar: "2.7g", protein: "4.5g", sodium: "480mg" },
    tags: ["Belgian European Can", "Resealable Freshness"],
    storage: "Store dry.",
    shelfLife: "Best Before: 15 months",
    bundleWith: ["drinks-dr-pepper", "sweets-kinder-bueno"],
    bundleTitle: "Movie Night Savoury & Sweet Stash",
    bundleDiscountPercent: 10,
  },
  {
    id: "crisps-doritos-nacho",
    name: "Doritos Nacho Cheese Tortilla Chips",
    brand: "Doritos",
    origin: "USA",
    flag: "🇺🇸",
    category: "crisps",
    price: 2150,
    unit: "198g party bag",
    emoji: "🧀",
    badge: "BESTSELLER",
    rating: 4.8,
    description: "Bold American nacho cheese flavor blasted over crispy toasted triangular corn chips. Perfect on their own or loaded with salsa and guacamole.",
    ingredients: ["Corn", "Vegetable oil (corn, canola, sunflower)", "Maltodextrin", "Salt", "Cheddar cheese (milk, cheese cultures, salt, enzymes)", "Whey", "Monosodium glutamate"],
    nutrition: { calories: "150 kcal / 28g", servingSize: "28g (approx 12 chips)", fat: "8g", sugar: "1g", protein: "2g", sodium: "210mg" },
    tags: ["USA Direct", "Bold Nacho Cheese", "Party Size"],
    storage: "Seal tightly.",
    shelfLife: "Best Before: 8 months",
    bundleWith: ["drinks-dr-pepper", "sweets-reeses-peanut"],
    bundleTitle: "American Party Night Duo",
    bundleDiscountPercent: 10,
  },
  {
    id: "crisps-lays-truffle",
    name: "Lay's Gourmet Black Truffle Potato Chips",
    brand: "Lay's",
    origin: "Thailand",
    flag: "🇹🇭",
    category: "crisps",
    price: 1850,
    unit: "105g bag",
    emoji: "🍄",
    badge: "NEW",
    rating: 4.7,
    description: "Thinly cut golden potato crisps infused with aromatic French black summer truffle seasoning. Sophisticated, earthy, and richly aromatic.",
    ingredients: ["Potatoes 62%", "Rice bran oil 31%", "Black Truffle Seasoning 7% (maltodextrin, sugar, salt, natural black truffle aroma)"],
    nutrition: { calories: "160 kcal / 30g", servingSize: "30g", fat: "10g", sugar: "1g", protein: "2g", sodium: "170mg" },
    tags: ["Gourmet Import", "Black Truffle Aroma"],
    storage: "Keep in a cool dry pantry.",
    shelfLife: "Best Before: 7 months",
    bundleWith: ["sweets-lindt-70", "drinks-arizona-green"],
    bundleTitle: "Gourmet Aisle Tasting Pair",
    bundleDiscountPercent: 10,
  },

  // ==================== 7. BABY PRODUCTS ====================
  {
    id: "baby-aptamil-gold-1",
    name: "Aptamil Gold+ Infant Formula Stage 1",
    brand: "Aptamil",
    origin: "New Zealand",
    flag: "🇳🇿",
    category: "baby",
    price: 12500,
    unit: "900g tin",
    emoji: "🍼",
    badge: "BESTSELLER",
    rating: 4.9,
    description: "Premium scientifically researched infant formula from New Zealand dairy. Contains Prebiotics (scGOS/lcFOS 9:1), Probiotics (Bifidobacterium breve), DHA Omega-3, and 16 essential vitamins and minerals for babies 0–6 months.",
    ingredients: ["Milk solids (demineralised whey, lactose, skim milk)", "Vegetable oils", "Galacto-oligosaccharides (GOS)", "Fish oil (DHA)", "Bifidobacterium breve M-16V", "Nucleotides"],
    nutrition: { calories: "66 kcal / 100ml prepared", servingSize: "1 scoop (7.3g)", fat: "3.4g", protein: "1.4g", carbohydrate: "7.4g" },
    tags: ["New Zealand Direct", "Stage 1 (0-6M)", "DHA Omega-3", "Authentic QR Verified"],
    storage: "Store in a cool dry place. Use contents within 4 weeks of opening.",
    shelfLife: "Best Before: 24 months",
    bundleWith: ["baby-aveeno-wash", "baby-organix-apple-puree"],
    bundleTitle: "New Mother's Complete Infant Care Kit",
    bundleDiscountPercent: 10,
    reviews: [
      { id: "r7", author: "Dr. Nilusha S.", location: "Dehiwala", rating: 5, date: "5 days ago", comment: "100% genuine New Zealand tin with tamper-evident seal. Fast delivery to Kalubowila.", verified: true }
    ],
  },
  {
    id: "baby-aveeno-wash",
    name: "Aveeno Baby Daily Care Hair & Body Wash",
    brand: "Aveeno",
    origin: "USA",
    flag: "🇺🇸",
    category: "baby",
    price: 4650,
    unit: "354ml pump bottle",
    emoji: "🧼",
    badge: "BESTSELLER",
    rating: 4.9,
    description: "Paediatrician-recommended tear-free daily cleanser formulated with natural colloidal oat extract. Gently cleanses baby's delicate skin and hair without drying.",
    ingredients: ["Water", "Cocamidopropyl Betaine", "Sodium Lauroamphoacetate", "Glycerin", "Coco-Glucoside", "Avena Sativa (Oat) Kernel Extract", "Polyquaternium-10"],
    tags: ["USA Direct", "Paediatrician Tested", "Tear-Free", "Soap & Dye Free"],
    storage: "Room temperature.",
    shelfLife: "Best Before: 30 months",
    bundleWith: ["baby-aptamil-gold-1", "baby-organix-apple-puree"],
    bundleTitle: "Gentle Bath & Feed Bundle",
    bundleDiscountPercent: 10,
  },
  {
    id: "baby-organix-apple-puree",
    name: "Organix Organic Apple & Raspberry Puree Pouch",
    brand: "Organix",
    origin: "United Kingdom",
    flag: "🇬🇧",
    category: "baby",
    price: 950,
    unit: "100g pouch",
    emoji: "🍎",
    rating: 4.8,
    description: "100% certified organic fruit puree for weaning babies 6+ months. No added sugar, no artificial thickeners, just pure crushed organic apples and ripe raspberries.",
    ingredients: ["Organic apples 85%", "Organic raspberries 15%"],
    nutrition: { calories: "48 kcal / pouch", servingSize: "100g", fat: "<0.5g", sugar: "10g (natural fruit sugar)", protein: "<0.5g" },
    tags: ["UK Certified Organic", "Stage 2 (6M+)", "No Added Sugar", "Gluten Free"],
    storage: "Store in ambient pantry. Refrigerate after opening and consume within 24 hours.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["baby-aptamil-gold-1", "baby-aveeno-wash"],
    bundleTitle: "Organic Weaning & Baby Care Pack",
    bundleDiscountPercent: 10,
  },

  // ==================== 8. CUPBOARD ====================
  {
    id: "cupboard-lotus-spread",
    name: "Lotus Biscoff Smooth Spread Jar",
    brand: "Lotus Biscoff",
    origin: "Belgium",
    flag: "🇧🇪",
    category: "cupboard",
    price: 3450,
    originalPrice: 3850,
    unit: "400g glass jar",
    emoji: "🫙",
    badge: "BESTSELLER",
    rating: 5.0,
    description: "The world-famous Belgian spread made directly from freshly crushed Lotus Biscoff cookies. Irresistibly smooth with caramelized cinnamon notes. Perfect on toast, waffles, or by the spoonful.",
    ingredients: ["Original caramelised biscuits 58% (wheat flour, sugar, vegetable oils, candy sugar syrup, sodium hydrogen carbonate, soy flour, salt, cinnamon)", "Rapeseed oil", "Sugar", "Emulsifier (soy lecithin)", "Acid (citric acid)"],
    nutrition: { calories: "584 kcal / 100g", servingSize: "15g (1 tbsp)", fat: "38.1g", sugar: "36.8g", protein: "2.9g", sodium: "210mg" },
    tags: ["Belgian Direct", "Vegan", "Nut Free", "No Added Colors"],
    storage: "Store at room temperature between 17°C and 22°C. Do NOT refrigerate.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["biscuits-lotus-biscoff-250", "sweets-lindt-70"],
    bundleTitle: "The Grand Lotus Biscoff Duo",
    bundleDiscountPercent: 12,
    reviews: [
      { id: "r8", author: "Hansi D.", location: "Colombo 05", rating: 5, date: "4 days ago", comment: "So addictive on morning toast. Arrived in heavy bubble wrap.", verified: true }
    ],
  },
  {
    id: "cupboard-nutella-750",
    name: "Nutella Hazelnut Spread with Cocoa Family Jar",
    brand: "Nutella",
    origin: "Italy",
    flag: "🇮🇹",
    category: "cupboard",
    price: 4850,
    unit: "750g jar",
    emoji: "🌰",
    badge: "BESTSELLER",
    rating: 4.9,
    description: "The gold standard of breakfast spreads. Made with quality roasted hazelnuts, skimmed milk, and cocoa. Direct European import with rich creamy consistency.",
    ingredients: ["Sugar", "Palm oil", "Hazelnuts (13%)", "Skimmed milk powder (8.7%)", "Fat-reduced cocoa (7.4%)", "Emulsifiers: lecithins (soya)", "Vanillin"],
    nutrition: { calories: "539 kcal / 100g", servingSize: "15g", fat: "30.9g", sugar: "56.3g", protein: "6.3g", sodium: "40mg" },
    tags: ["Italian Import", "Family 750g Jar", "Vegetarian", "Gluten Free"],
    storage: "Store at room temperature 18°C – 24°C.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["biscuits-nutella-biscuits", "sweets-kinder-bueno"],
    bundleTitle: "Nutella Ultimate Breakfast Basket",
    bundleDiscountPercent: 12,
  },
  {
    id: "cupboard-barilla-penne",
    name: "Barilla Penne Rigate No. 73 Italian Pasta",
    brand: "Barilla",
    origin: "Italy",
    flag: "🇮🇹",
    category: "cupboard",
    price: 1350,
    unit: "500g box",
    emoji: "🍝",
    rating: 4.8,
    description: "Italy's #1 pasta made from 100% select durum wheat semolina. Ridged Penne shape holds rich tomato, pesto, and creamy cheese sauces perfectly al dente in 11 minutes.",
    ingredients: ["100% Durum wheat semolina", "Water"],
    nutrition: { calories: "359 kcal / 100g", servingSize: "85g dry", fat: "2g", sugar: "3.5g", protein: "12g", sodium: "5mg" },
    tags: ["Italian Direct", "100% Durum Semolina", "Non-GMO Verified"],
    storage: "Store in a dry cupboard.",
    shelfLife: "Best Before: 32 months",
    bundleWith: ["cupboard-nescafe-gold", "frozen-anchor-butter"],
    bundleTitle: "Italian Home Chef Pantry Trio",
    bundleDiscountPercent: 10,
  },
  {
    id: "cupboard-nescafe-gold",
    name: "Nescafé Gold Blend Arabica Instant Coffee",
    brand: "Nescafé",
    origin: "United Kingdom",
    flag: "🇬🇧",
    category: "cupboard",
    price: 4950,
    originalPrice: 5500,
    unit: "200g glass jar",
    emoji: "☕",
    badge: "HOT DEAL",
    rating: 4.9,
    description: "Expertly crafted premium roast instant coffee blending mountain-grown Arabica beans ground 10 times finer for smooth rich aroma and golden crema.",
    ingredients: ["100% Pure instant coffee", "Roast and ground Arabica coffee (3%)"],
    nutrition: { calories: "2 kcal / cup", servingSize: "1.8g (1 tsp)", fat: "0g", sugar: "0g", protein: "0.2g", sodium: "0mg" },
    tags: ["UK Direct", "Golden Arabica Roast", "200g Jar (111 Cups)"],
    storage: "Close tightly after use. Store in a dry cupboard.",
    shelfLife: "Best Before: 24 months",
    bundleWith: ["biscuits-lotus-biscoff-250", "sweets-toblerone"],
    bundleTitle: "Executive Morning Coffee & Biscuit Pair",
    bundleDiscountPercent: 12,
  },

  // ==================== 9. FROZEN ====================
  {
    id: "frozen-haagendazs-choc",
    name: "Häagen-Dazs Belgian Dark Chocolate Ice Cream",
    brand: "Häagen-Dazs",
    origin: "France",
    flag: "🇫🇷",
    category: "frozen",
    price: 4950,
    unit: "460ml tub",
    emoji: "🍨",
    badge: "BESTSELLER",
    rating: 4.9,
    image: "/images/products/frozen-haagendazs.png",
    description: "Rich dark chocolate ice cream made with real French cream, fresh milk, and decadent ribbons of Belgian dark chocolate shavings. Ultra-creamy with no artificial stabilizers.",
    ingredients: ["Fresh cream (29.2%)", "Condensed skimmed milk", "Sugar", "Belgian chocolate 13% (cocoa mass, sugar, cocoa butter, emulsifier: soy lecithin, natural vanilla)", "Egg yolk", "Cocoa powder"],
    nutrition: { calories: "313 kcal / 100g", servingSize: "86g (2 scoops)", fat: "19.9g", sugar: "26.3g", protein: "4.8g", sodium: "60mg" },
    tags: ["French Direct", "100% Real Cream", "Insulated Delivery", "Vegetarian"],
    storage: "Keep frozen at -18°C. Shipped in thermal insulated bags with icepacks.",
    shelfLife: "Best Before: 18 months",
    bundleWith: ["biscuits-timtam-orig", "sweets-lindt-70"],
    bundleTitle: "Late-Night Ice Cream & Cookie Parlor Pack",
    bundleDiscountPercent: 15,
    reviews: [
      { id: "r9", author: "Faris A.", location: "Wellawatte", rating: 5, date: "3 days ago", comment: "Arrived ice-cold in Colombo traffic with dry-pack insulation. Top tier!", verified: true }
    ],
  },
  {
    id: "frozen-little-moons",
    name: "Little Moons Mango Ice Cream Mochi",
    brand: "Little Moons",
    origin: "United Kingdom",
    flag: "🇬🇧",
    category: "frozen",
    price: 3950,
    unit: "6-piece box",
    emoji: "🍡",
    badge: "NEW",
    rating: 4.8,
    description: "Chewy sweet rice dough (mochi) wrapping smooth artisan Alphonso mango gelato. Only 76 calories per mochi bite.",
    ingredients: ["Mango puree 25%", "Whole milk", "Sugar", "Rice flour", "Water", "Fresh cream", "Trehalose"],
    nutrition: { calories: "76 kcal / mochi", servingSize: "1 piece (32g)", fat: "1.8g", sugar: "11g", protein: "1.1g" },
    tags: ["UK Direct", "Gluten Free", "76 kcal per bite"],
    storage: "Keep frozen at -18°C.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["drinks-ramune-soda", "sweets-milka-oreo"],
    bundleTitle: "Japanese Street Snack Mochi Trio",
    bundleDiscountPercent: 10,
  },
  {
    id: "frozen-anchor-butter",
    name: "Anchor Pure Salted Creamery Butter",
    brand: "Anchor",
    origin: "New Zealand",
    flag: "🇳🇿",
    category: "frozen",
    price: 1450,
    unit: "227g block",
    emoji: "🧈",
    rating: 4.7,
    description: "100% pure butter from grass-fed New Zealand cows. Rich, golden, and naturally creamy for baking, cooking, and spreading.",
    ingredients: ["Pasteurised cream (from cow's milk)", "Salt"],
    nutrition: { calories: "720 kcal / 100g", servingSize: "10g", fat: "81.4g", sugar: "0.6g", protein: "0.7g", sodium: "600mg" },
    tags: ["New Zealand Grass-Fed", "100% Pure Cream", "No Additives"],
    storage: "Keep refrigerated below 4°C or freeze for long storage.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["cupboard-barilla-penne", "cupboard-lotus-spread"],
    bundleTitle: "Essential Kitchen Staple Bundle",
    bundleDiscountPercent: 10,
  },

  // ==================== 10. VIRAL PRODUCTS (LIMITED TIME ONLY) ====================
  {
    id: "viral-dubai-kunafa-choc",
    name: "Dubai Pistachio Kunafa Milk Chocolate",
    brand: "Fix Dessert Chocolatier",
    origin: "UAE",
    flag: "🇦🇪",
    category: "viral",
    price: 5850,
    originalPrice: 6500,
    unit: "200g viral bar",
    emoji: "✨",
    badge: "VIRAL",
    rating: 5.0,
    stockLeft: 6,
    isViral: true,
    description: "The #1 viral chocolate sensation across TikTok and Instagram! Handcrafted thick Swiss-style milk chocolate shell filled with crunchy roasted shredded filo pastry (kunafa), pure pistachio butter, and tahini cream. Direct air-freight import from Dubai.",
    ingredients: ["Milk chocolate 45% (sugar, cocoa butter, whole milk powder, cocoa mass)", "Roasted kataifi filo pastry (wheat flour, water, salt)", "Pure pistachio paste 25%", "Tahini (sesame seed paste)", "Clarified butter (ghee)"],
    nutrition: { calories: "540 kcal / 100g", servingSize: "35g (1 heavy square)", fat: "34g", sugar: "42g", protein: "8.5g", sodium: "90mg" },
    tags: ["Direct Dubai Air-Freight", "Handcrafted", "Limited Stock", "TikTok Viral"],
    storage: "Store in a cool dry area at 16°C – 19°C. Best enjoyed at room temp for oozy pistachio center.",
    shelfLife: "Best Before: 4 months from small-batch production",
    bundleWith: ["crisps-takis-blue-heat", "drinks-prime-hydration"],
    bundleTitle: "The Internet's #1 Viral Taste Test Box",
    bundleDiscountPercent: 15,
    reviews: [
      { id: "r10", author: "Zahra H.", location: "Colombo 03", rating: 5, date: "Yesterday", comment: "The crunch of the kunafa with the pistachio cream is insane. Worth every rupee!", verified: true },
      { id: "r11", author: "Ashan W.", location: "Dehiwala", rating: 5, date: "3 days ago", comment: "Real authentic Fix bar, not a knockoff. Hand delivered within 2 hours in Kalubowila.", verified: true },
    ],
  },
  {
    id: "viral-samyang-buldak-2x",
    name: "Samyang Buldak 2x Spicy Hot Chicken Ramen",
    brand: "Samyang",
    origin: "South Korea",
    flag: "🇰🇷",
    category: "viral",
    price: 1150,
    unit: "140g pack",
    emoji: "🔥",
    badge: "VIRAL",
    rating: 4.9,
    stockLeft: 18,
    isViral: true,
    image: "/images/products/noodle-samyang.png",
    description: "The viral Korean Fire Noodle challenge champion! Rated at 8,808 Scoville Heat Units, featuring chewy thick noodles and an intensely spicy stir-fry sauce with roasted sesame and nori flakes.",
    ingredients: ["Noodle 75.8% (wheat flour, tapioca starch, palm oil, wheat gluten)", "Sauce 23.3% (water, soy sauce, sugar, artificial chicken flavor, chili pepper powder, habanero chili, garlic)", "Flake 0.9% (roasted sesame, roasted laver)"],
    nutrition: { calories: "550 kcal / pack", servingSize: "140g prepared", fat: "17g", sugar: "8g", protein: "13g", sodium: "1350mg" },
    tags: ["Korean Direct", "8,808 SHU Scoville", "Halal Certified (KMF)", "Viral Challenge"],
    storage: "Store dry.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["drinks-arizona-green", "viral-takis-blue-heat"],
    bundleTitle: "Extreme Heat & Cool Down Challenge Set",
    bundleDiscountPercent: 12,
    reviews: [
      { id: "r12", author: "Dinuk P.", location: "Moratuwa", rating: 5, date: "2 days ago", comment: "Deadly spicy! Definitely get the AriZona green tea with it to survive.", verified: true }
    ],
  },
  {
    id: "viral-takis-blue-heat",
    name: "Takis Blue Heat Spicy Rolled Tortilla Chips",
    brand: "Takis",
    origin: "Mexico",
    flag: "🇲🇽",
    category: "viral",
    price: 2450,
    originalPrice: 2850,
    unit: "280g mega bag",
    emoji: "💙",
    badge: "LIMITED TIME",
    rating: 4.7,
    stockLeft: 6,
    isViral: true,
    description: "Rolled corn tortilla chips blasted with electric blue seasoning that combines fiery hot chili peppers with an intense splash of lime. Leaves your tongue electric blue!",
    ingredients: ["Corn masa flour", "Vegetable oil", "Seasoning (maltodextrin, citric acid, sugar, potassium chloride, salt, MSG, Blue 1 Lake, natural chili aroma)"],
    nutrition: { calories: "150 kcal / 28g", servingSize: "28g", fat: "8g", sugar: "1g", protein: "2g", sodium: "410mg" },
    tags: ["Authentic Mexican Import", "Electric Blue Tongue", "Extreme Heat"],
    storage: "Seal tightly.",
    shelfLife: "Best Before: 8 months",
    bundleWith: ["viral-dubai-kunafa-choc", "drinks-prime-hydration"],
    bundleTitle: "Viral Blue Heat & Sweet Combo",
    bundleDiscountPercent: 15,
  },
  {
    id: "viral-prime-glowberry",
    name: "Prime Hydration Drink 'Glowberry' Limited",
    brand: "Prime",
    origin: "USA",
    flag: "🇺🇸",
    category: "viral",
    price: 2950,
    unit: "500ml bottle",
    emoji: "🧪",
    badge: "LIMITED TIME",
    rating: 4.8,
    stockLeft: 8,
    isViral: true,
    description: "Ultra-rare Glowberry limited edition glow-in-the-dark bottle. Packed with 10% coconut water, electrolytes, and crisp sour green apple berry flavor.",
    ingredients: ["Filtered water", "Coconut water (10%)", "Citric acid", "Dipotassium phosphate", "Magnesium", "Natural flavors", "BCAAs", "Vitamin B12 & B6"],
    nutrition: { calories: "20 kcal", servingSize: "500ml", fat: "0g", sugar: "2g", protein: "0g", sodium: "10mg" },
    tags: ["Ultra Rare Drop", "Glow in Dark Bottle", "Electrolytes"],
    storage: "Serve chilled.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["viral-feastables-mrbeast", "viral-samyang-buldak-2x"],
    bundleTitle: "Collector's Limited Edition Snack Drop",
    bundleDiscountPercent: 12,
  },
  {
    id: "viral-feastables-mrbeast",
    name: "Feastables MrBeast Milk Crunch Bar",
    brand: "Feastables",
    origin: "USA",
    flag: "🇺🇸",
    category: "viral",
    price: 2650,
    unit: "60g bar",
    emoji: "🍫",
    badge: "LIMITED TIME",
    rating: 4.8,
    stockLeft: 12,
    isViral: true,
    description: "MrBeast's reformulated Feastables recipe made with simple ingredients: organic cocoa, 100% grass-fed milk, and crispy puffed rice. Taste test beats Hershey's in blind tastings.",
    ingredients: ["Milk chocolate (cane sugar, whole milk powder, organic cocoa butter, organic chocolate liquor, organic vanilla powder)", "Crisped rice (rice flour, sugar, salt)"],
    nutrition: { calories: "320 kcal / bar", servingSize: "60g", fat: "20g", sugar: "27g", protein: "5g", sodium: "75mg" },
    tags: ["MrBeast Official", "Grass-Fed Milk", "Simple 6 Ingredients"],
    storage: "Keep in a cool dry space.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["viral-dubai-kunafa-choc", "drinks-prime-hydration"],
    bundleTitle: "MrBeast & Dubai Viral Choc Drop",
    bundleDiscountPercent: 15,
  },
  {
    id: "viral-buldak-carbonara",
    name: "Samyang Buldak Creamy Carbonara Ramen",
    brand: "Samyang",
    origin: "South Korea",
    flag: "🇰🇷",
    category: "viral",
    price: 1250,
    unit: "130g pack",
    emoji: "🍜",
    badge: "VIRAL",
    rating: 4.9,
    stockLeft: 16,
    isViral: true,
    description: "The most popular Buldak variant! Combines the spicy fire chicken stir-fry sauce with creamy Italian mozzarella cheese and butter powder to create a velvety pink carbonara.",
    ingredients: ["Wheat flour noodles", "Buldak spicy chicken sauce", "Carbonara powder (whole milk powder, cheese powder, butter powder, parsley flakes)"],
    nutrition: { calories: "550 kcal / pack", servingSize: "130g", fat: "20g", sugar: "5g", protein: "10g", sodium: "1330mg" },
    tags: ["Korean Direct", "Creamy Pink Carbonara", "Halal Certified"],
    storage: "Store dry.",
    shelfLife: "Best Before: 12 months",
    bundleWith: ["drinks-ramune-soda", "biscuits-oreo-japan-matcha"],
    bundleTitle: "Seoul Street Food Carbonara Set",
    bundleDiscountPercent: 10,
  },
];

// Helper Functions
export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function productsByCategory(slug: string): Product[] {
  return PRODUCTS.filter((p) => p.category === slug);
}

export function categoryCount(slug: string): number {
  return productsByCategory(slug).length;
}

export function getViralProducts(): Product[] {
  return PRODUCTS.filter((p) => p.isViral || p.category === "viral");
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter((p) => p.id !== product.id && p.category === product.category).slice(0, limit);
}

export function getBundleProducts(product: Product): { items: Product[]; discountPercent: number; bundleTitle: string } {
  let bundleItems: Product[] = [];
  if (product.bundleWith && product.bundleWith.length > 0) {
    bundleItems = product.bundleWith
      .map((id) => PRODUCTS.find((p) => p.id === id))
      .filter((p): p is Product => Boolean(p));
  }
  if (bundleItems.length < 2) {
    const others = PRODUCTS.filter((p) => p.id !== product.id && !bundleItems.some((b) => b.id === p.id));
    const drinkOrSnack = others.find((p) => p.category === "drinks" || p.category === "biscuits" || p.category === "crisps");
    if (drinkOrSnack && !bundleItems.some((b) => b.id === drinkOrSnack.id)) {
      bundleItems.push(drinkOrSnack);
    }
    const another = others.find((p) => !bundleItems.some((b) => b.id === p.id));
    if (another && bundleItems.length < 2) {
      bundleItems.push(another);
    }
  }
  return {
    items: [product, ...bundleItems.slice(0, 2)],
    discountPercent: product.bundleDiscountPercent || 10,
    bundleTitle: product.bundleTitle || `The ${product.brand} Convenience Combo`,
  };
}

export function getAvailableOrigins(): string[] {
  return Array.from(new Set(PRODUCTS.map((p) => p.origin))).sort();
}
